# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneSignalNotificationServiceExtension
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end

target 'WebViewGold' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebViewGold
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end
